"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

type OrderFormData = {
  customer_profile_id: string;
  medicine_name: string;
  quantity: number;
  notes?: string;
};

export async function submitOrder(formData: OrderFormData) {
  const supabase = await createClient();

  // Get customer profile for customer name and contact
  const { data: profile } = await (supabase as any)
    .from("customer_profiles")
    .select("full_name, phone, email")
    .eq("id", formData.customer_profile_id)
    .single();

  if (!profile) {
    return { success: false, error: "Customer profile not found" };
  }

  const { data: order, error } = await (supabase as any)
    .from("order_requests")
    .insert({
      customer_profile_id: formData.customer_profile_id,
      customer_name: profile.full_name,
      customer_phone: profile.phone,
      customer_email: profile.email,
      medicine_name: formData.medicine_name,
      quantity: formData.quantity,
      notes: formData.notes || null,
      status: "pending",
    })
    .select()
    .single();

  if (error) {
    console.error("Order submission error:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/profile");
  revalidatePath("/dashboard/orders");

  // Return the pickup code that was auto-generated by the trigger
  return { 
    success: true, 
    pickupCode: order?.pickup_code || "",
    orderId: order?.id 
  };
}

